telegram_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: 12345678
      port: 5432
      dbname: raw_telegram
      schema: public
      threads: 4
