name: Run Telegram Scraper

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    environment: env

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Export environment variables
      run: |
        echo "API_ID=${{ vars.API_ID }}" >> $GITHUB_ENV
        echo "API_HASH=${{ vars.API_HASH }}" >> $GITHUB_ENV

    - name: Run Telegram scraper
      run: |
        python scripts/scrape_data.py
