name: Data Pipeline & YOLO Object Detection

on:
  push:
    branches:
      - main
      - Task-*

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


  data_scraping:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Data Scraping
        run: |
          python scripts/scrape_data.py
  
      - name: Upload Scraped Data
        uses: actions/upload-artifact@v4
        with:
          name: scraped-data
          path: data/raw/

  data_cleaning:
    needs: data_scraping
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Scraped Data
        uses: actions/download-artifact@v4
        with:
          name: scraped-data
          path: data/raw/

      - name: Install dbt and Dependencies
        run: |
          pip install dbt-core dbt-postgres
          dbt deps

      - name: Run Data Cleaning & Transformation
        run: |
          dbt run

      - name: Upload Cleaned Data
        uses: actions/upload-artifact@v4
        with:
          name: cleaned-data
          path: data/processed/

  yolo_object_detection:
    needs: data_cleaning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download Cleaned Data
        uses: actions/download-artifact@v4
        with:
          name: cleaned-data
          path: data/processed/

      - name: Install YOLO Dependencies
        run: |
          pip install torch torchvision
          pip install ultralytics

      - name: Train YOLO Model
        run: |
          python scripts/train_yolo.py

      - name: Run Object Detection
        run: |
          python scripts/detect_objects.py

      - name: Upload YOLO Model & Results
        uses: actions/upload-artifact@v4
        with:
          name: yolo-results
          path: results/
